INSERT INTO hotel_006 (hotel_no, name, address) 
	 SELECT 'H1', 'PURI', 'PURI' FROM dual UNION ALL 
	 SELECT 'H2','TAJ', 'MUMBAI' FROM dual UNION ALL 
	 SELECT 'H3', 'SONALI', 'PURI' FROM dual UNION ALL 
	 SELECT 'H4', 'ITC', 'KOLKATA' FROM dual UNION ALL 
	 SELECT 'H5', 'PARK', 'CHENNAI' FROM dual UNION ALL 
	 SELECT 'H6', 'SAMUDRA', 'CHENNAI' FROM dual;
