INSERT INTO guest_006 (guest_no, name, address)
	 SELECT 'G1', 'RAJA', 'MUMBAI' FROM dual UNION ALL 
	 SELECT 'G2', 'SIMA', 'KOLKATA' FROM dual UNION ALL 
	 SELECT 'G3', 'RAHUL', 'KOLKATA' FROM dual UNION ALL 
	 SELECT 'G4', 'MILI', 'KOLKATA' FROM dual UNION ALL 
	 SELECT 'G5', 'SMITH', 'CHENNAI' FROM dual UNION ALL 
	 SELECT 'G6', 'JONES', 'CHENNAI' FROM dual UNION ALL 
	 SELECT 'G7', 'RIMI', 'KOLKATA' FROM dual UNION ALL 
	 SELECT 'G8', 'REKHA', 'CHENNAI' FROM dual UNION ALL 
	 SELECT 'G9', 'RISHI', 'PURI' FROM dual;
