INSERT INTO HOTEL_006 VALUES ('H1','GRAND','KOLKATA');
INSERT INTO HOTEL_006 VALUES ('H2','TAJ','MUMBAI');
INSERT INTO HOTEL_006 VALUES ('H3','PURI','PURI');
INSERT INTO HOTEL_006 VALUES ('H4','ITC','KOLKATA');
INSERT INTO HOTEL_006 VALUES ('H5','PARK','CHENNAI');
INSERT INTO HOTEL_006 VALUES ('H6','ITC','MUMBAI');
INSERT INTO HOTEL_006 VALUES ('H7','SONALI','PURI');