INSERT INTO guest_006 (guest_no, name, address) VALUES ('G1', 'RAM', 'MUMBAI');
INSERT INTO guest_006 (guest_no, name, address) VALUES ('G2', 'SIMA', 'KOLKATA');
INSERT INTO guest_006 (guest_no, name, address) VALUES ('G3', 'RAHUL', 'KOLKATA');
INSERT INTO guest_006 (guest_no, name, address) VALUES ('G4', 'MILI', 'KOLKATA');
INSERT INTO guest_006 (guest_no, name, address) VALUES ('G5', 'SMITH', 'CHENNAI');
INSERT INTO guest_006 (guest_no, name, address) VALUES ('G6', 'JONES', 'CHENNAI');
INSERT INTO guest_006 (guest_no, name, address) VALUES ('G7', 'RIMI', 'KOLKATA');
INSERT INTO guest_006 (guest_no, name, address) VALUES ('G8', 'REKHA', 'CHENNAI');
INSERT INTO guest_006 (guest_no, name, address) VALUES ('G9', 'RISHI', 'PURI');